server:
  port: 8080
spring:
  application:
    name: weddy
  profiles:
    active: common, user
  config:
    import: optional:configserver:http://15.164.159.172:8888
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product.default.svc.cluster.local:8080  # 여기 수정
          predicates:
            - Path=/api/products/**, /api/venders/**

        - id: schedule-service
          uri: http://schedule.default.svc.cluster.local:8080  # 여기도 수정
          predicates:
            - Path=/api/schedules/**

        - id: user-service
          uri: http://user.default.svc.cluster.local:8080  # 여기도 수정
          predicates:
            - Path=/api/users/**, /api/payments/**, /api/contracts/**, /api/login/**, /api/oauth2/**


#        - id: order-service
#          uri: http://localhost:8082  # order-service? ??
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
