spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user1
    password: 123123123
  application:
    name: weddy
  profiles:
    active: common, user
  config:
    import: optional:configserver:http://15.164.159.172:8888
  cloud:
    gcp:
      storage:
        bucket: weddy
        project-id: sigma-outcome-440304-k4
        credentials:
          location: classpath:sigma-outcome-440304-k4-96c9253930d8.json


  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
# 이거 나중에 바꿔야함
server:
  port: 8080
